#include "World.h"
// Utilities
#include <iostream>
#include <fstream>
#include <string>
#include "string.h"
#include <vector>
#include "Constants.h"
#include "Ray.h"
#include "ShadeRec.h"
#include "Image.h"
// Tracers
#include "RayCast.h"
#include "Whitted.h"
#include "AreaLighting.h"
// GeometricObjects
#include "Plane.h"
#include "Sphere.h"
#include "Triangle.h"
#include "TriangleMesh.h"
#include "Rectangle.h"
#include "FastTriMesh.h"
#include "Instance.h"
#include "Deformed.h"
#include "CSG.h"
#include "SmoothMesh.h"
// Cameras
#include "Pinhole.h"
#include "Orthographic.h"
// Materials
#include "Matte.h"
#include "Phong.h"
#include "Reflective.h"
#include "Transparent.h"
#include "Emmissive.h"
#include "SV_Matte.h"
// Lights
#include "Ambient.h"
#include "Directional.h"
#include "Point.h"
#include "AreaLight.h"
// Acceleration
#include "BVH.h"
// Samplers
#include "Jittered.h"
// Mappings
#include "RectangularMap.h"
// Textures
#include "ImageTexture.h"
#include "ConstantColor.h"
#include "Checker.h"
#include "Noise.h"